// USTP CDO Campus Locations - Single source of truth for all location dropdowns
export const USTP_LOCATIONS = [
  "Administration Building",
  "Arts and Culture Building",
  "Blank",
  "BTED",
  "Cafeteria",
  "Civil Technology Building (Big)",
  "Civil Technology Building (small)",
  "Culinary Arts Building",
  "Dr. Rotoras Memorial Statue",
  "Engineering Complex I",
  "Engineering Complex II",
  "FIC Extension",
  "Finance and Accounting Building",
  "Food innovation",
  "Girl's Trade Building",
  "Guidance and Testing Center",
  "Gym Lobby",
  "Gymnasium",
  "Information and Communication Technology Center",
  "ITB Building",
  "LRC Building",
  "Near Administration Building",
  "Near Arts and Culture Building",
  "Near Blank",
  "Near BTED",
  "Near Cafeteria",
  "Near Civil Technology Building (Big)",
  "Near Civil Technology Building (Small)",
  "Near Culinary Arts Building",
  "Near Dr. Rotoras Memorial Statue",
  "Near Engineering Complex I",
  "Near Engineering Complex II",
  "Near FIC Extension",
  "Near Finance and Accounting Building",
  "Near Food innovation",
  "Near Girl's Trade Building",
  "Near Guidance and Testing Center",
  "Near Gym Lobby",
  "Near Gymnasium",
  "Near Information and Communication Technology Center",
  "Near ITB Building",
  "Near LRC Building",
  "Near New Clinic Building",
  "Near Old Civil Engineering Building",
  "Near Parking Lot A",
  "Near Parking Lot B",
  "Near Printing Press",
  "Near residences",
  "Near Science Centrum",
  "Near Science Complex Building",
  "Near SPED Center",
  "Near Sports Complex",
  "Near Student Center",
  "Near Student Lounge",
  "Near Study Shed",
  "Near Study Shed 2",
  "Near Study Shed 3",
  "Near Study Shed 4",
  "Near Study Shed 5",
  "Near Study Shed 6",
  "Near Sump Pit",
  "Near Technology Building",
  "Near Old Civil Engineering Building",
  "New Clinic Building",
  "Old Civil Engineering Building",
  "Parking Lot A",
  "Parking Lot B",
  "Printing Press",
  "residences",
  "Science Centrum",
  "Science Complex Building",
  "SPED Center",
  "Sports Complex",
  "Student Center",
  "Student Lounge",
  "Study Shed",
  "Study Shed 2",
  "Study Shed 3",
  "Study Shed 4",
  "Study Shed 5",
  "Study Shed 6",
  "Sump Pit",
  "Technology Building",
];
