// USTP CDO Campus Locations - Single source of truth for all location dropdowns
export const USTP_LOCATIONS = [
  "Gymnasium",
  "Cafeteria",
  "Culinary Arts Building",
  "Science Complex Building",
  "Old Civil Engineering Building",
  "Science Centrum",
  "Engineering Complex II",
  "Student Lounge",
  "LRC Building",
  "New Clinic Building",
  "Parking Lot A",
  "Parking Lot B",
  "Engineering Complex I",
  "Gym Lobby",
  "Information and Communication Technology Center",
  "Finance and Accounting Building",
  "Food innovation",
  "residences",
  "FIC Extension",
  "Study Shed",
  "Study Shed 2",
  "Guidance and Testing Center",
  "Arts and Culture Building",
  "Study Shed 3",
  "Study Shed 4",
  "Study Shed 5",
  "Technology Building",
  "Student Center",
  "BTED",
  "Blank",
  "Sports Complex",
  "Dr. Rotoras Memorial Statue",
  "Administration Building",
  "Civil Technology Building (small)",
  "Civil Technology Building (Big)",
  "Sump Pit",
  "Girl's Trade Building",
  "Printing Press",
  "Study Shed 6",
  "ITB Building",
  "SPED Center",
  "Near Gymnasium",
  "Near Cafeteria",
  "Near Culinary Arts Building",
  "Near Science Complex Building",
  "Near Old Civil Engineering Building",
  "Near Science Centrum",
  "Near Engineering Complex II",
  "Near Student Lounge",
  "Near LRC Building",
  "Near New Clinic Building",
  "Near Parking Lot A",
  "Near Parking Lot B",
  "Near Engineering Complex I",
  "Near Gym Lobby",
  "Near Information and Communication Technology Center",
  "Near Finance and Accounting Building",
  "Near Food innovation",
  "Near residences",
  "Near FIC Extension",
  "Near Study Shed",
  "Near Study Shed 2",
  "Near Guidance and Testing Center",
  "Near Arts and Culture Building",
  "Near Study Shed 3",
  "Near Study Shed 4",
  "Near Study Shed 5",
  "Near Technology Building",
  "Near Student Center",
  "Near BTED",
  "Near Blank",
  "Near Sports Complex",
  "Near Dr. Rotoras Memorial Statue",
  "Near Administration Building",
  "Near Civil Technology Building (small)",
  "Near Civil Technology Building (Big)",
  "Near Sump Pit",
  "Near Girl's Trade Building",
  "Near Printing Press",
  "Near Study Shed 6",
  "Near ITB Building",
  "Near SPED Center"
];
